### ISSUE TITLE
Failure to provide response

### ISSUE THREAD

**Issue by chattertechno** [LockwoodTech/Flutter_USSD_SDK#1]
In the current hover docs many things have changed.
This app can't process the actions following your tutorial in Medium.
If possible can you update this app and functions.

**Comment by LockwoodTech** [comment]
Sure i will work on it

**Comment by oilman20** [comment]
Okay

Let’s me see to it, if you can give me access

**Comment by chattertechno** [comment]
Clone the repo. And follow some basic steps in installation to see the problem.

**Comment by chattertechno** [comment]
@LockwoodTech I have configured and it seems like working well but i got a problem here 
![Screenshot_20200807-215913](https://user-images.githubusercontent.com/44748636/89679213-5869b380-d8f9-11ea-813b-9f56289cf603.png)

**Comment by chattertechno** [comment]
As you can see the mobile data is on.
The app is allowed on all needed permissions.
I think the problem is coming from Hover version or other error from hover.

**Comment by oilman20** [comment]
Okay dear

**Comment by oilman20** [comment]
Check your internet connection

**Comment by chattertechno** [comment]
There is internet connection so I don't know what's the problem

**Comment by LockwoodTech** [comment]
Hover needs to update actions from time to time so just uninstall the demo and run a new install with internet connected

**Comment by oilman20** [comment]
Okay dear

**Comment by chattertechno** [comment]
@LockwoodTech I tried with but it returns the same as the screenshot above.

**Comment by chattertechno** [comment]
I have resolved this issue I will have a pull request in order to provide fixes and addition of the current flutter and hover upgrades.

**Comment by oilman20** [comment]
Have you fit the problem and can we collaborate together
